#!/usr/bin/env python3
"""One NAND primitive per pinned TapeOut record. No synthesis or optimization."""
import argparse
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from golden import Netlist


def sources():
    data = json.loads((HERE / 'sources.json').read_text())
    for name, s in data.items():
        raw = bytes.fromhex(s['netlist_hex'])
        if hashlib.sha256(raw).hexdigest() != s['sha256']:
            raise ValueError(f'{name}: source hash mismatch')
        net = Netlist.decode(raw, s['n_in'], s['n_out'])
        if net.n_state or len(net.records) != s['n_nand'] or not 0 < len(net.records) <= 4000:
            raise ValueError(f'{name}: expected a small, combinational NAND netlist')
    return data


def emit_verilog(name, s):
    net = Netlist.decode(bytes.fromhex(s['netlist_hex']), s['n_in'], s['n_out'])
    total = 2 + net.n_in + len(net.records)
    lines = [
        '// AUTO-GENERATED by gen_verilog.py from sources.json. DO NOT EDIT.',
        f"// Source SHA-256: {s['sha256']}",
        f'// {len(net.records)} NAND records, {net.n_in} inputs, {net.n_out} outputs, last_outs.',
        '`default_nettype none',
        f'module {name}(input wire [{net.n_in-1}:0] din, output wire [{net.n_out-1}:0] dout);',
        "    wire w0 = 1'b0;",
        "    wire w1 = 1'b1;",
    ]
    # Scalar nets avoid whole-vector event fanout in event-driven simulators.
    lines.extend(f'    wire w{i+2} = din[{i}];' for i in range(net.n_in))
    for i, (op, a, b) in enumerate(net.records):
        if op != 0:
            raise ValueError('combinational NAND records only')
        lines.append(f'    wire w{net.n_in+2+i}; nand g{i}(w{net.n_in+2+i}, w{a}, w{b});')
    output_wires = ', '.join(f'w{i}' for i in range(total-1, total-net.n_out-1, -1))
    lines.extend([f'    assign dout = {{{output_wires}}};',
                  'endmodule', '`default_nettype wire', ''])
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true', help='refuse stale or hand-edited RTL')
    args = ap.parse_args()
    for name, s in sources().items():
        path = HERE.parent / 'src' / (name + '.v')
        expected = emit_verilog(name, s)
        if args.check:
            if path.read_text() != expected:
                raise SystemExit(f'stale generated RTL: {path}')
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_text(expected)
        print(f"{'checked' if args.check else 'wrote'} {name}: {s['n_nand']} NAND, SHA {s['sha256']}")


if __name__ == '__main__':
    main()
