// AUTO-GENERATED by gen_verilog.py from sources.json. DO NOT EDIT.
// Source SHA-256: f35baa03be7f9eefba33d778e0ff5b6e1430ccbb7b5b4a9daa81695b186c26c0
// 21 NAND records, 15 inputs, 2 outputs, last_outs.
`default_nettype none
module cell_279(input wire [14:0] din, output wire [1:0] dout);
    wire w0 = 1'b0;
    wire w1 = 1'b1;
    wire w2 = din[0];
    wire w3 = din[1];
    wire w4 = din[2];
    wire w5 = din[3];
    wire w6 = din[4];
    wire w7 = din[5];
    wire w8 = din[6];
    wire w9 = din[7];
    wire w10 = din[8];
    wire w11 = din[9];
    wire w12 = din[10];
    wire w13 = din[11];
    wire w14 = din[12];
    wire w15 = din[13];
    wire w16 = din[14];
    wire w17; nand g0(w17, w3, w3);
    wire w18; nand g1(w18, w15, w17);
    wire w19; nand g2(w19, w18, w18);
    wire w20; nand g3(w20, w17, w17);
    wire w21; nand g4(w21, w15, w15);
    wire w22; nand g5(w22, w20, w21);
    wire w23; nand g6(w23, w10, w19);
    wire w24; nand g7(w24, w13, w22);
    wire w25; nand g8(w25, w7, w7);
    wire w26; nand g9(w26, w12, w25);
    wire w27; nand g10(w27, w23, w24);
    wire w28; nand g11(w28, w27, w27);
    wire w29; nand g12(w29, w5, w28);
    wire w30; nand g13(w30, w6, w6);
    wire w31; nand g14(w31, w11, w30);
    wire w32; nand g15(w32, w31, w31);
    wire w33; nand g16(w33, w29, w29);
    wire w34; nand g17(w34, w26, w33);
    wire w35; nand g18(w35, w32, w32);
    wire w36; nand g19(w36, w34, w34);
    wire w37; nand g20(w37, w24, w35);
    assign dout = {w37, w36};
endmodule
`default_nettype wire
